name: edutrust-backend
namespace: backend
# This is a Helm chart for deploying the Edutrust backend application.
# It includes configurations for replica count, image repository, service type, and ingress settings.
# The chart is designed to be flexible and can be customized as needed.
# The default settings are provided, but users can override them in their own values.yaml file.
replicaCount: 3 
image: 
  repository : gautamabhis/edutrust-backend
  tag: "build-11"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
ingress:
  enabled: true
  name: edutrust-ingress
  host: edutrust
resources:
  limits:
    memory: "256Mi"
    cpu: "200m"
  requests:
    memory: "128Mi"
    cpu: "100m"
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
