apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.name }}-role
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "secrets"]
    verbs: [ "create", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.name }}-rolebinding
  namespace: {{ .Values.namespace }}  
subjects:
  - kind: ServiceAccount
    name: {{ .Values.name }}-serviceaccount
    namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.name }}-role
  apiGroup: rbac.authorization.k8s.io
---apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-serviceaccount
  namespace: {{ .Values.namespace }}
automountServiceAccountToken: true